version: "3.7"
services:
  influxdb:
    # image: influxdb:2.3
    # image: influxdb:latest
    image: influxdb:1.8.4
    container_name: influxdb
    hostname: homeserver
    # environment:
    #   - INFLUXDB_DATA_CACHE_SNAPSHOT_WRITE_COLD_DURATION= 25m
      # - INFLUXDB_DB=speedtests
      # - INFLUXDB_ADMIN_USER=admin
      # - INFLUXDB_ADMIN_PASSWORD=adminpass
    volumes:
      - influxdb_data:/var/lib/influxdb
    ports:
      - 8086:8086
  # influxdb_cli:
  #   links:
  #     - influxdb
  #   image: influxdb:latest
  #   entrypoint: influx setup --bucket test_bucket -t test_token -o test_org --username=test_username --password=test_password --host=http://influxdb:8086 -f

  #   # restart: on-failure:20
  #   depends_on:
  #     - influxdb
  speedtest:
    image: barrycarey/speedtest-for-influxdb-and-grafana
    container_name: speedtest
    depends_on:
      - influxdb
      # - influxdb_cli
    volumes:
      - ./config.ini:/src/config.ini
    # restart: always
volumes:
  influxdb_data:
